version: '3'
services:
    app:
        build: .
        container_name: p000-app
        entrypoint: dockerize -template ./.docker/app/.env:.env -template ./.docker/app/.env.testing:.env.testing php-fpm
        environment:
            - _DB_HOST=p000-db
            - _DB_DATABASE=p000
            - _DB_USERNAME=root
            - _DB_PASSWORD=root
            - _DB_DATABASE_TEST=p000_test
        volumes:
            - .:/var/www:delegated
        networks:
            - app-network
        depends_on:
            - db
    nginx:
        build: .docker/nginx
        container_name: p000-nginx
        restart: always
        tty: true
        ports:
            - "8010:80"
        volumes:
            - .:/var/www:delegated
        networks:
            - app-network
        depends_on:
            - app
    db:
        image: mariadb
        command: --innodb-use-native-aio=0
        container_name: p000-db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=p110
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network
    postgres:
        image: postgres
        container_name: postgres
        restart: unless-stopped
        # volumes:
            #  - postgres:/var/lib/postgresql/data
        # - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - app-network
        ports:
            - 5432:5432

networks:
    app-network:
        driver: bridge
